### ISSUE TITLE
Add an option to revert the order

### ISSUE THREAD

**Issue by KaiMartin** [cosmocode/changes#25]
Currently, the changes plugin is hard coded to list changes from old to new. By contrast, the last changes  function integrated in dokuwiki lists from new to old.

Please add an option to revert the order of the output.

---<)kmk(>---

**Comment by splitbrain** [comment]
I do not understand. The plugin already lists the newest changes first. Are you asking for being able to list the oldest changes first?

**Comment by KaiMartin** [comment]
Errr, yes. I meant to ask for oldest changes on top, new changes on bottom. 
Sorry for the confusion.
---<)kaimartin(>---

**Comment by splitbrain** [comment]
I see. Can you explain the use case?

**Comment by CFenner** [comment]
I would also like to request a reverse flag, because my list is from oldest to newest and I would like to see the most recent changes at the top...

<img width="415" alt="bildschirmfoto 2015-09-27 um 22 04 20" src="https://cloud.githubusercontent.com/assets/9592452/10124947/c8ff560e-6563-11e5-9efb-322b0246d1b9.png">

**Comment by moz0817** [comment]
I have the same sort order like CFenner, **oldest on top**, only in one wiki-animal of my farm. The other ones have normal sort order. Very strange!

**Comment by moz0817** [comment]
Possibly the option `listmedia` cause this behavior. Since I disabled it, I've proper sort order (newest on top). A review in my other wikis, confirm my guess.
